version: '3'

services:
  frontend:
    image: kleinspeedy/langhelp-frontend:latest

  backend:
    image: kleinspeedy/langhelp-backend:latest
    depends_on:
      - database

  database:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=secure
    ports:
      - 33060:3306
    volumes:
      - mysql:/var/lib/mysql

  nginx-proxy:
    image: nginx:1.21-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:rw
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend
      - database

volumes:
  mysql: